Documentation update
damb/scdetect pull request #65
Opened 2021-11-22 15:21 UTC by mmesim

I updated the template attributes to include `"arrivalOffsetThreshold"` because the example is a multi-stream template configuration. That will help not to forget about the offset when trying multi-channel/station detections.

2021-11-22 15:51 UTC, mmesim commented
@damb: If you agree with the changes proposed on the [last commit](https://github.com/damb/scdetect/pull/65/commits/c2caad79463652f33e048f3ce8ea8de1f214ab3b), then you can close issue [#58](https://github.com/damb/scdetect/issues/58)

2021-11-29 09:19 UTC, damb commented
Also, please stick to 80 chars per line.

2021-11-29 09:23 UTC, damb commented
Once you're done, please merge the two commits regarding the *arrivalOffsetThreshold*.

2021-11-29 09:25 UTC, damb commented on README.md
> +    "arrivalOffsetThreshold":"",
If disabling the `arrivalOffsetThreshold` is required, set the value to `0.000002` (which is the default). This is due to SeisComP's `Core::Time` supports microsecond accuracy.

I'm not sure if a string is accepted, at all.

2021-11-29 09:25 UTC, damb commented on README.md
> +    "arrivalOffsetThreshold":"",
see above

2021-11-29 09:25 UTC, damb commented on README.md
> +all SeisComP modules implementing SeisComP's `StreamApplication` interface.) combined with a local archive.
I'd prefer not to mention the local archive, here, since a user can specify any RecordStream via the CLI (i.e. even a real-time RecordStream). Instead you could add the note on *local archives* below e.g.

> In case of combining the RecordStream with a local archive, records must be sorted by end time ...

2021-12-13 13:13 UTC, mmesim commented on README.md
> +    "arrivalOffsetThreshold":"",
@damb 
I edited the README.md file. You can proceed, if you agree, with the merge.

2021-12-14 09:31 UTC, damb requested changes
@mmesim, sorry for being picky.

- Please, use meaningful commit messages.
- Also, see the comments inline.

2021-12-14 09:31 UTC, damb commented on README.md
> +all SeisComP modules implementing SeisComP's `StreamApplication` interface).
Please, add the missing dot, again.

2021-12-14 09:31 UTC, damb commented on README.md
> +In case of combing RecordStream with a local archive, records must be <br/>**sorted by end time**, especially in the case of multistream detection. <br/> This could be easily done using [scmssort](ht
When asking for 80 chars per line, I was referring to the formatting of the file (i.e. the `README.md`), and not the rendering of the `README.md`. (I didn't ask you to add `<br/>`s ;).)

Note that an IDE/editor may be configured to do this kind of formatting work for you. You shouldn't be bothered with such kind of toil.

2021-12-14 09:31 UTC, damb commented on src/apps/scdetect/CMakeLists.txt
> +add_definitions(
Please remove this change. I assume, this wasn't on purpose.

2021-12-14 10:36 UTC, mmesim commented
Go ahead and do any change you'd like! I give up!!

2021-12-14 11:04 UTC, damb commented
> Go ahead and do any change you'd like! I give up!!

Come on, @mmesim. Give it a try!

2021-12-21 08:36 UTC, damb commented
Superseded by #73.

2021-12-21 08:36 UTC, closed without merging